/**
 * Order Service Layer
 * Handles all order-related business logic and database operations
 */

import Order, { IOrder } from '../db/models/Order';
import Product from '../db/models/Product';
import connectDB from '../db/mongodb';
import { OrderCreateInput, OrderUpdateInput, OrderStatus } from '../../types/order.types';
import { NotFoundError, ValidationError } from '../utils/errors';
import { logger } from '../utils/logger';
import mongoose from 'mongoose';

/**
 * Order filter options for querying
 */
export interface OrderFilterOptions {
  status?: OrderStatus;
  customerEmail?: string;
  page?: number;
  limit?: number;
}

/**
 * Paginated order response
 */
export interface PaginatedOrderResponse {
  orders: IOrder[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Create a new order with automatic order number generation
 * Validates that all referenced products exist
 * @param input - Order creation data
 * @returns Created order document
 * @throws ValidationError if order data is invalid or products don't exist
 */
export async function createOrder(input: OrderCreateInput): Promise<IOrder> {
  try {
    await connectDB();
    
    logger.info('Creating new order', { 
      customerEmail: input.customerEmail,
      itemCount: input.items.length 
    });
    
    // Validate that all products exist and get their details
    const productIds = input.items.map(item => item.productId);
    const products = await Product.find({ 
      _id: { $in: productIds },
      isActive: true 
    });
    
    if (products.length !== productIds.length) {
      const foundIds = products.map(p => p._id.toString());
      const missingIds = productIds.filter(id => !foundIds.includes(id));
      throw new ValidationError(
        'Invalid product references',
        { products: [`Products not found or inactive: ${missingIds.join(', ')}`] }
      );
    }
    
    // Build order items with product details
    const orderItems = input.items.map(item => {
      const product = products.find(p => p._id.toString() === item.productId);
      if (!product) {
        throw new ValidationError('Product not found', { productId: [item.productId] });
      }
      
      return {
        productId: new mongoose.Types.ObjectId(item.productId),
        productName: product.name,
        quantity: item.quantity,
        priceAtTime: product.price,
      };
    });
    
    // Create order (order number will be auto-generated by pre-save hook)
    const order = new Order({
      customerName: input.customerName,
      customerEmail: input.customerEmail,
      customerPhone: input.customerPhone,
      items: orderItems,
      message: input.message,
      status: 'new',
      shippingAddress: input.shippingAddress,
    });
    
    await order.save();
    
    logger.info('Order created successfully', { 
      orderId: order._id,
      orderNumber: order.orderNumber,
      customerEmail: order.customerEmail
    });
    
    return order;
  } catch (error) {
    logger.error('Failed to create order', { error, input });
    
    if (error instanceof ValidationError) {
      throw error;
    }
    
    if (error instanceof Error && error.name === 'ValidationError') {
      throw new ValidationError('Order validation failed', { general: [error.message] });
    }
    
    throw error;
  }
}

/**
 * Get a single order by ID
 * @param id - Order ID
 * @returns Order document
 * @throws NotFoundError if order doesn't exist
 */
export async function getOrderById(id: string): Promise<IOrder> {
  try {
    await connectDB();
    
    logger.info('Fetching order by ID', { id });
    
    const order = await Order.findById(id).lean();
    
    if (!order) {
      throw new NotFoundError(`Order with id '${id}' not found`);
    }
    
    logger.info('Order fetched successfully', { id, orderNumber: order.orderNumber });
    
    return order as unknown as IOrder;
  } catch (error) {
    logger.error('Failed to fetch order by ID', { error, id });
    
    if (error instanceof NotFoundError) {
      throw error;
    }
    
    throw error;
  }
}

/**
 * Get all orders with pagination and filtering (admin only)
 * @param options - Filter and pagination options
 * @returns Paginated order list sorted by creation date (newest first)
 */
export async function getAllOrders(
  options: OrderFilterOptions = {}
): Promise<PaginatedOrderResponse> {
  try {
    await connectDB();
    
    const {
      status,
      customerEmail,
      page = 1,
      limit = 20,
    } = options;
    
    logger.info('Fetching all orders', { options });
    
    // Build query filter
    const filter: any = {};
    
    if (status) {
      filter.status = status;
    }
    
    if (customerEmail) {
      filter.customerEmail = customerEmail.toLowerCase();
    }
    
    // Calculate pagination
    const skip = (page - 1) * limit;
    
    // Execute query with pagination, sorted by creation date descending
    const [orders, total] = await Promise.all([
      Order.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Order.countDocuments(filter),
    ]);
    
    const totalPages = Math.ceil(total / limit);
    
    logger.info('Orders fetched successfully', { 
      count: orders.length, 
      total, 
      page, 
      totalPages 
    });
    
    return {
      orders: orders as unknown as IOrder[],
      total,
      page,
      limit,
      totalPages,
    };
  } catch (error) {
    logger.error('Failed to fetch orders', { error, options });
    throw error;
  }
}

/**
 * Update order status (admin only)
 * Validates status transitions according to state machine rules
 * @param id - Order ID
 * @param input - Order update data (typically status)
 * @returns Updated order document
 * @throws NotFoundError if order doesn't exist
 * @throws ValidationError if status transition is invalid
 */
export async function updateOrderStatus(
  id: string,
  input: OrderUpdateInput
): Promise<IOrder> {
  try {
    await connectDB();
    
    logger.info('Updating order status', { id, newStatus: input.status });
    
    // Find order first to validate status transition
    const order = await Order.findById(id);
    
    if (!order) {
      throw new NotFoundError(`Order with id '${id}' not found`);
    }
    
    // Validate status transition if status is being updated
    if (input.status && input.status !== order.status) {
      if (!order.canTransitionTo(input.status)) {
        throw new ValidationError(
          'Invalid status transition',
          { status: [`Cannot transition from ${order.status} to ${input.status}`] }
        );
      }
      
      order.status = input.status;
    }
    
    // Update message if provided
    if (input.message !== undefined) {
      order.message = input.message;
    }
    
    await order.save();
    
    logger.info('Order updated successfully', { 
      id, 
      orderNumber: order.orderNumber,
      newStatus: order.status 
    });
    
    return order;
  } catch (error) {
    logger.error('Failed to update order', { error, id, input });
    
    if (error instanceof NotFoundError || error instanceof ValidationError) {
      throw error;
    }
    
    if (error instanceof Error && error.name === 'ValidationError') {
      throw new ValidationError('Order validation failed', { general: [error.message] });
    }
    
    throw error;
  }
}

/**
 * Get order by order number
 * @param orderNumber - Unique order number
 * @returns Order document
 * @throws NotFoundError if order doesn't exist
 */
export async function getOrderByNumber(orderNumber: string): Promise<IOrder> {
  try {
    await connectDB();
    
    logger.info('Fetching order by order number', { orderNumber });
    
    const order = await Order.findOne({ orderNumber }).lean();
    
    if (!order) {
      throw new NotFoundError(`Order with order number '${orderNumber}' not found`);
    }
    
    logger.info('Order fetched successfully', { orderNumber, id: order._id });
    
    return order as unknown as IOrder;
  } catch (error) {
    logger.error('Failed to fetch order by order number', { error, orderNumber });
    
    if (error instanceof NotFoundError) {
      throw error;
    }
    
    throw error;
  }
}

/**
 * Get recent orders (for admin dashboard)
 * @param limit - Maximum number of orders to return (default: 10)
 * @returns Array of recent orders sorted by creation date
 */
export async function getRecentOrders(limit: number = 10): Promise<IOrder[]> {
  try {
    await connectDB();
    
    logger.info('Fetching recent orders', { limit });
    
    const orders = await Order.find()
      .sort({ createdAt: -1 })
      .limit(limit)
      .lean();
    
    logger.info('Recent orders fetched successfully', { count: orders.length });
    
    return orders as unknown as IOrder[];
  } catch (error) {
    logger.error('Failed to fetch recent orders', { error, limit });
    throw error;
  }
}

/**
 * Get order count by status (for admin dashboard statistics)
 * @param status - Optional status filter
 * @returns Count of orders matching the status
 */
export async function getOrderCount(status?: OrderStatus): Promise<number> {
  try {
    await connectDB();
    
    const filter = status ? { status } : {};
    
    logger.info('Counting orders', { status });
    
    const count = await Order.countDocuments(filter);
    
    logger.info('Order count retrieved', { status, count });
    
    return count;
  } catch (error) {
    logger.error('Failed to count orders', { error, status });
    throw error;
  }
}
